name: dynamicbind
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - backports.zstd=1.2.0=py310h69bd2ac_0
  - blas=1.0=mkl
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.1=0
  - cuda-version=11.8=h70ddcb2_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - ffmpeg=4.4.0=hca11adc_2
  - filelock=3.20.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - greenlet=3.3.0=py310hea6c23e_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=20_linux64_mkl
  - libboost=1.86.0=hed09d94_4
  - libboost-python=1.86.0=py310hc563356_5
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.9.0=20_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.53=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - librdkit=2025.09.3=h3c5c181_0
  - libsqlite=3.51.1=h0c1763c_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.3=h5347b49_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_2
  - pcre2=10.47=haa7fec5_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.29.0=py310h8c3e0f7_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.4.0=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - rdkit=2025.09.3=py310hd71299c_0
  - readline=8.3=h853b02a_0
  - reportlab=4.4.7=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.45=py310h7c4b9e2_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.13=noxft_ha0e22de_103
  - torchaudio=2.4.0=py310_cu124
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu124
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!161.3030=h7f98852_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - attrs==25.4.0
      - biopython==1.79
      - distro==1.9.0
      - e3nn==0.5.9
      - fair-esm==2.0.0
      - joblib==1.5.3
      - numpy==1.23.5
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - psutil==7.1.3
      - rustworkx==0.17.1
      - scipy==1.15.3
      - spyrmsd==0.9.0
      - torch-cluster==1.6.3+pt24cu124
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt24cu124
      - torch-sparse==0.6.18+pt24cu124
      - torch-spline-conv==1.2.2+pt24cu124
      - tqdm==4.67.1
      - xxhash==3.6.0
prefix: /home/dzeiberg/miniconda3/envs/dynamicbind
