name: relax
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h5d8c7f2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - ambertools=24.8=cuda_None_nompi_py312hbe1986e_101
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_2
  - arpack=3.9.1=nompi_hf03ea27_102
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binutils=2.45=default_h4852527_105
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - binutils_linux-64=2.45=default_h4852527_105
  - biopython=1.86=py312h4c3975b_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py312hdb49522_1
  - bson=0.5.10=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.22.0=hc31b594_1
  - c-compiler=1.10.0=h2b85faf_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-option-group=0.5.6=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda-gcc-specs=13.4.0=h109b0d3_16
  - contourpy=1.3.3=py312hd9148b4_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cccl_linux-64=12.8.90=ha770c72_1
  - cuda-command-line-tools=12.8.1=ha770c72_0
  - cuda-compiler=12.8.1=hbad6d8a_0
  - cuda-crt-dev_linux-64=12.8.93=ha770c72_3
  - cuda-crt-tools=12.8.93=ha770c72_3
  - cuda-cudart=12.8.90=h5888daf_1
  - cuda-cudart-dev=12.8.90=h5888daf_1
  - cuda-cudart-dev_linux-64=12.8.90=h3f2d84a_1
  - cuda-cudart-static=12.8.90=h5888daf_1
  - cuda-cudart-static_linux-64=12.8.90=h3f2d84a_1
  - cuda-cudart_linux-64=12.8.90=h3f2d84a_1
  - cuda-cuobjdump=12.8.90=hbd13f7d_1
  - cuda-cupti=12.8.90=h5888daf_1
  - cuda-cupti-dev=12.8.90=h5888daf_1
  - cuda-cuxxfilt=12.8.90=hbd13f7d_1
  - cuda-driver-dev=12.8.90=h5888daf_1
  - cuda-driver-dev_linux-64=12.8.90=h3f2d84a_1
  - cuda-gdb=12.8.90=ha677faa_1
  - cuda-libraries=12.8.1=ha770c72_0
  - cuda-libraries-dev=12.8.1=ha770c72_0
  - cuda-nsight=12.8.90=h7938cbb_1
  - cuda-nvcc=12.8.93=hcdd1206_2
  - cuda-nvcc-dev_linux-64=12.8.93=he91c749_3
  - cuda-nvcc-impl=12.8.93=h85509e4_3
  - cuda-nvcc-tools=12.8.93=he02047a_3
  - cuda-nvcc_linux-64=12.8.93=he0b4e1d_2
  - cuda-nvdisasm=12.8.90=hbd13f7d_1
  - cuda-nvml-dev=12.8.90=hbd13f7d_1
  - cuda-nvprof=12.8.90=hcf8d014_1
  - cuda-nvprune=12.8.90=hbd13f7d_1
  - cuda-nvrtc=12.8.93=h5888daf_1
  - cuda-nvrtc-dev=12.8.93=h5888daf_1
  - cuda-nvtx=12.8.90=h5888daf_1
  - cuda-nvvm-dev_linux-64=12.8.93=ha770c72_3
  - cuda-nvvm-impl=12.8.93=he02047a_3
  - cuda-nvvm-tools=12.8.93=he02047a_3
  - cuda-nvvp=12.8.93=hbd13f7d_1
  - cuda-opencl=12.8.90=h5888daf_1
  - cuda-opencl-dev=12.8.90=h5888daf_1
  - cuda-profiler-api=12.8.90=h7938cbb_1
  - cuda-sanitizer-api=12.8.93=hbd13f7d_1
  - cuda-toolkit=12.8.1=ha804496_0
  - cuda-tools=12.8.1=ha770c72_0
  - cuda-version=12.8=h5d125a7_3
  - cuda-visual-tools=12.8.1=ha770c72_0
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cusparselt=0.6.3.2=hdea8103_1
  - cxx-compiler=1.10.0=h1a2810e_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h3b011a4_111
  - filelock=3.20.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h8a5da7c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gcc=13.4.0=h0dff253_16
  - gcc_impl_linux-64=13.4.0=hf787b08_16
  - gcc_linux-64=13.4.0=h0a5b801_17
  - gds-tools=1.13.1.3=h5888daf_1
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_2
  - greenlet=3.3.0=py312h1289d80_0
  - gxx=13.4.0=h7467c50_7
  - gxx_impl_linux-64=13.4.0=h6a38259_16
  - gxx_linux-64=13.4.0=h50488e6_17
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kernel-headers_linux-64=5.14.0=he073ed8_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.86.0=hed09d94_4
  - libboost-python=1.86.0=py312hf890105_5
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libcublas=12.8.4.1=h9ab20c4_1
  - libcublas-dev=12.8.4.1=h9ab20c4_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.3.3.83=h5888daf_1
  - libcufft-dev=11.3.3.83=h5888daf_1
  - libcufile=1.13.1.3=h628e99a_1
  - libcufile-dev=1.13.1.3=h5888daf_1
  - libcurand=10.3.9.90=h9ab20c4_1
  - libcurand-dev=10.3.9.90=h9ab20c4_1
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.7.3.90=h9ab20c4_1
  - libcusolver-dev=11.7.3.90=h9ab20c4_1
  - libcusparse=12.5.8.93=h5888daf_1
  - libcusparse-dev=12.5.8.93=h5888daf_1
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=13.4.0=hd1d28cc_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h566cb83_2
  - libnetcdf=4.9.2=nompi_h21f7587_118
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.3.3.100=h9ab20c4_1
  - libnpp-dev=12.3.3.100=h9ab20c4_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvfatbin=12.8.90=h5888daf_1
  - libnvfatbin-dev=12.8.90=h5888daf_1
  - libnvjitlink=12.8.93=h5888daf_1
  - libnvjitlink-dev=12.8.93=h5888daf_1
  - libnvjpeg=12.3.5.92=h5888daf_1
  - libnvjpeg-dev=12.3.5.92=ha770c72_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpng=1.6.53=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libprotobuf=5.28.3=h6128344_1
  - librdkit=2025.09.4=h3c5c181_0
  - libsanitizer=13.4.0=h2a15e64_16
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=13.4.0=h6963c3b_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.5.1=cuda126_generic_hb23410f_208
  - libudev1=258.3=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxkbfile=1.1.0=h166bdaf_1
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - lxml=6.0.2=py312h70dad80_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdtraj=1.11.0=np2py312h8baca0b_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.0.0=hacee8c2_941
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py312h8a5da7c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nccl=2.29.2.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.2=nompi_h5aa5643_101
  - networkx=3.6.1=pyhcf101f3_0
  - nomkl=3.0=0
  - notebook=7.5.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nsight-compute=2025.1.1.2=hb5ebaad_1
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numexpr=2.14.1=py312h88efc94_101
  - numpy=2.2.6=py312h72c5963_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - ocl-icd-system=1.0.0=1
  - openblas=0.3.30=pthreads_h6ec200e_4
  - opencl-headers=2025.06.13=h5888daf_0
  - openff-amber-ff-ports=2025.09.0=pyhd8ed1ab_0
  - openff-forcefields=2025.10.1=pyhd8ed1ab_0
  - openff-interchange=0.4.10=pyhd8ed1ab_0
  - openff-interchange-base=0.4.10=pyhd8ed1ab_0
  - openff-nagl=0.5.4=pyhd8ed1ab_1
  - openff-nagl-base=0.5.4=pyhd8ed1ab_1
  - openff-nagl-models=2025.9.0=pyhd8ed1ab_0
  - openff-toolkit=0.18.0=pyhd8ed1ab_0
  - openff-toolkit-base=0.18.0=pyhd8ed1ab_0
  - openff-units=0.3.1=pyhd8ed1ab_2
  - openff-utilities=0.1.16=pyhd8ed1ab_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openmm=8.4.0=py312h50c43f0_0
  - openmmforcefields=0.15.1=pyhcf101f3_0
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmed=4.3.0=py312ha9124a0_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pdb-tools=2.5.0=pyhd8ed1ab_1
  - pdbfixer=1.12=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py312h50c33e8_0
  - pint=0.24.4=pyhe01879c_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.2.1=py312h5253ce2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycairo=1.29.0=py312h2596900_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.10=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h680f630_0
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py312hefc0c3f_10
  - python=3.12.12=hd63d673_1_cpython
  - python-constraint=1.4.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytorch=2.5.1=cuda126_generic_py312_hdd128b7_208
  - pytorch-lightning=2.6.0=pyhcf101f3_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - rdkit=2025.09.4=py312h3ecb6ed_0
  - rdma-core=60.0=hecca717_0
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - reportlab=4.4.7=py312h4c3975b_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - rocm-core=7.0.2=h54a6638_0
  - rpds-py=0.30.0=py312h868fb18_0
  - scipy=1.16.3=py312h54fa4ab_2
  - send2trash=2.0.0=pyha191276_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlalchemy=2.0.45=py312h4c3975b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.34=h087de78_3
  - tbb=2022.3.0=h8d10470_1
  - tbb-devel=2022.3.0=h74b38a2_1
  - terminado=0.18.1=pyhc90fa1f_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tinydb=4.8.2=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - triton=3.1.0=cuda126py312h776fbae_6
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - validators=0.35.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py312h8a5da7c_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - Jinja2==3.1.5
    - MarkupSafe==3.0.2
    - Pygments==2.19.1
    - asttokens==3.0.0
    - decorator==5.1.1
    - executing==2.1.0
    - filelock==3.16.1
    - fsspec==2024.12.0
    - ipython==8.31.0
    - jedi==0.19.2
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - networkx==3.4.2
    - parso==0.8.4
    - pexpect==4.9.0
    - prompt_toolkit==3.0.48
    - protobuf==5.29.3
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - regex==2024.11.6
    - safetensors==0.5.2
    - sentencepiece==0.2.0
    - six==1.17.0
    - stack-data==0.6.3
    - tokenizers==0.21.0
    - traitlets==5.14.3
    - tzdata==2024.2
    - wcwidth==0.2.13

prefix: "/home/dzeiberg/micromamba/envs/relax"
